name: ar_build
on: [push]
jobs:
  run-check:
    if: "contains(github.event.head_commit.message, '[ci]')"
    runs-on: ubuntu-latest
    container: quay.io/wslh-bioinformatics/ar-report:1.0.0
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run AR Report Build Test
        env:
          NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
        run: |
          ./test.sh
